// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Standard eBooks Browser",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Standard eBooks Browser",
            targets: ["AppModule"],
            bundleIdentifier: "com.bdirgo.standardebooksbrowser",
            teamIdentifier: "B5ZM7GP533",
            displayVersion: "1.0",
            bundleVersion: "20",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: "public.app-category.books"
        )
    ],
    dependencies: [
        .package(url: "https://github.com/CoreOffice/XMLCoder", "0.13.1"..<"1.0.0"),
        .package(url: "https://github.com/lorenzofiamingo/swiftui-cached-async-image", "2.1.1"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "XMLCoder", package: "XMLCoder"),
                .product(name: "CachedAsyncImage", package: "swiftui-cached-async-image")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
